python mountain.py test_images/mountain.jpg mountain.jpg 3 4
python mountain.py test_images/mountain2.jpg mountain2.jpg 3 4
python mountain.py test_images/mountain3.jpg mountain3.jpg 3 4
python mountain.py test_images/mountain4.jpg mountain4.jpg 3 4
python mountain.py test_images/mountain5.jpg mountain5.jpg 3 4
python mountain.py test_images/mountain6.jpg mountain6.jpg 3 4
python mountain.py test_images/mountain7.jpg mountain7.jpg 3 4
python mountain.py test_images/mountain8.jpg mountain8.jpg 3 4
python mountain.py test_images/mountain9.jpg mountain9.jpg 3 4
